/* Generated by automated build script */
#define SNAPSHOT
#define TEXTVER "Development snapshot 2015-02-09.a87a14a"
#define SSHVER "PuTTY-Snapshot-2015-02-09.a87a14a"
#define BINARY_VERSION 0,63,10475,0
